name: Stock Alert

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stock-alert:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_IDS: ${{ secrets.CHAT_IDS }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_ID: ${{ secrets.CONSUMER_ID }}
      MOBILE: ${{ secrets.MOBILE }}
      MPIN: ${{ secrets.MPIN }}
      TOTP_SECRET: ${{ secrets.TOTP_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build
        run: mvn clean package -DskipTests

      - name: Check Kotak environment
        run: |
          if [ -z "$CONSUMER_KEY" ]; then
            echo "CONSUMER_KEY is NOT available"
          else
            echo "CONSUMER_KEY is available"
          fi

          if [ -z "$CONSUMER_ID" ]; then
            echo "CONSUMER_ID is NOT available"
          else
            echo "CONSUMER_ID is available"
          fi

          if [ -z "$TOTP_SECRET" ]; then
            echo "TOTP_SECRET is NOT available"
          else
            echo "TOTP_SECRET is available"
          fi

      - name: Run Application
        run: java -jar target/*.jar